service:
  name: workshop

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  # NOTE: This needs to be way more secure
  iamRoleStatements:
    - Effect: "Allow"
      Action: "*"
      Resource: "*"

custom:
  webpack:
    includeModules: true

functions:
  graphql:
    handler: src/handlers.graphql
    events:
      - http:
          method: ANY
          path: graphql
          cors: true
